apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: waysd8hpp-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: waysd8hpp-go 
  name: waysd8hpp-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: waysd8hpp-go 
